baseURL = "https://neoZPT.github.io/my-awesome-blog/"
title = "我的第一座數字花園"
languageCode = "zh-tw"
theme = "PaperMod"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首頁"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "關於我"
    url = "/about/"
    weight = 3

[params]
  homeInfoParams = { Title = "哈囉，我是志平！", Content = "這裡是我的數字花園，分享技術、生活與創作。" }
  defaultTheme = "dark"           # 預設深色模式
  disableThemeToggle = false       # 顯示深/淺色切換
  ShowShareButtons = true          # 文章分享按鈕
  ShowReadingTime = true           # 顯示閱讀時間
  ShowToc = true                   # 顯示目錄
  ShowBreadCrumbs = true           # 顯示麵包屑
  ShowCodeCopyButtons = true       # 程式碼區塊複製
  ShowPostNavLinks = true          # 上一篇/下一篇
  ShowWordCount = true             # 顯示字數
  ShowRssButtonInSectionTermList = true # RSS 按鈕
  ShowAllPagesInArchive = true     # 歷史文章全顯示
  ShowPageNums = true              # 分頁顯示
  ShowLastMod = true               # 顯示最後修改時間
  ShowTag = true                   # 顯示標籤
  ShowCategory = true              # 顯示分類
  ShowComments = false             # 若要開啟評論可改 true
  comments = false
  socialIcons = [
    { name = "github", url = "https://github.com/NeoZPT" },
    { name = "linkedin", url = "https://linkedin.com/in/你的帳號" },
    { name = "twitter", url = "https://twitter.com/你的帳號" }
  ]
  assets = { favicon = "/images/favicon.ico", favicon16x16 = "/images/favicon-16x16.png", favicon32x32 = "/images/favicon-32x32.png", apple_touch_icon = "/images/apple-touch-icon.png", safari_pinned_tab = "/images/safari-pinned-tab.svg" }

[params.profileMode]
  enabled = true
  title = "嗨!我是志平，也可以叫我Neo"
  subtitle = "這裡是我的自我介紹，歡迎交流！"
  imageUrl = "Me.jpg"
  imageTitle = "我的頭像"
  imageWidth = 120
  imageHeight = 120

[[params.profileMode_buttons]]
  name = "GitHub"
  url = "https://github.com/NeoZPT"

[[params.profileMode_buttons]]
  name = "LinkedIn"
  url = "https://linkedin.com/in/你的帳號"

[[params.profileMode_buttons]]
  name = "Twitter"
  url = "https://twitter.com/你的帳號"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[services]
  [services.googleAnalytics]
    id = ""
